language: node_js
node_js:
- node
script:
- 
deploy:
  provider: firebase
  token: 
env:
  global:
  - secure: aJgbFlHRFp10RftpyE51ziASv4PYnqLGeSG908S3uyT9t4uzqWrdrtBPAIfypT7xwp9Zhm4k29L4TD6Ij7G3Y55eVw9R/JKWDC9y7Nk7VWRLdgBlkyvZq2UkL52nS5mhMaFM51bo4D9HdYE1cBFl5sJNXT9PVIcrOI2tDVTSTIyfWP8fsG4wRnRJmw45G1q24ywj6J03Bd00dwvuCwNb+yRZqcW32Zk1I5oU1DQtzZMRnFF/1XNqhxWPegKm0oQwixGvCmvhnaNY2vmH4MxfsYgxVJ6mBP1yf+DuvcDCjWsDN2oRxSTsXi1qBj84kESsh0WCDS3AXC7s74mSp9BMCNxXtjiEhX6rxelmGIKnxKh8oX9o/+LpdUZ3Tk6ODrnQaR4nBSXegLDl2qa4SIKZEKHH+DGq/oU5AZ+QUkpZiScC52BMmkEOjp/mKe+Y5rCG1ZveXZNcPJMc53RHnTfDL65rr1fizYOXp17EiWBDEmS7hcdmNBpasyLIikAk6eZ3ALWNEW4htNcCF3VWb0L16uLDLAlmWT2+4FIsLEgt/YFu3LUNsPv7j896H8R1UzLjFPFbJG7PeKMusW/vg9Nm7iUieOXVp90Cqq2YK9HFCY5hfy2lLY9MmtvvuGiQh174X9h9P65KX/juJWj1sFaE63+6IK8ImWsyC2+nx2O9EBc=
